name: Labeler
on:
  push:
    branches: [ main, new-snippets ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, new-snippets ]
    
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
